import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🤖 Final Production Modeling — Demand Forecasting\n",
    "\n",
    "This notebook implements the winning configurations found during research:\n",
    "1. **LightGBM**: Champion for granular item-level forecasting.\n",
    "2. **SARIMA**: Champion for aggregate daily trends."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "%pip install lightgbm pmdarima statsmodels pandas numpy matplotlib seaborn scikit-learn -q\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import warnings, time, pickle, os\n",
    "import gc\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error\n",
    "from sklearn.model_selection import TimeSeriesSplit\n",
    "import lightgbm as lgb\n",
    "from statsmodels.tsa.statespace.sarimax import SARIMAX\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "print(\"✅ Libraries imported.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Load & Prepare Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "data_dir = 'preprocessed_data'\n",
    "try:\n",
    "    X_train = pd.read_parquet(f'{data_dir}/X_train.parquet')\n",
    "    X_test = pd.read_parquet(f'{data_dir}/X_test.parquet')\n",
    "    y_train = pd.read_parquet(f'{data_dir}/y_train.parquet').iloc[:, 0]\n",
    "    y_test = pd.read_parquet(f'{data_dir}/y_test.parquet').iloc[:, 0]\n",
    "    with open(f'{data_dir}/feature_names.pkl', 'rb') as f:\n",
    "        FEATURES = pickle.load(f)\n",
    "    print(\"✅ Loaded data from parquet files.\")\n",
    "    print(\"\\nFeatures loaded:\")\n",
    "    print(FEATURES)\n",
    "except Exception as e:\n",
    "    print(\"⚠️ Parquet files not found. Please run preprocessing.ipynb first or ensure data is loaded.\")\n",
    "    raise e"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Cross-Validation (Time Series Split)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"🚀 Running TimeSeriesSplit (3 Folds) on LightGBM...\")\n",
    "tscv = TimeSeriesSplit(n_splits=3)\n",
    "fold = 1\n",
    "for train_idx, val_idx in tscv.split(X_train):\n",
    "    print(f\"--- Fold {fold} ---\")\n",
    "    X_cv_train = X_train.iloc[train_idx]\n",
    "    y_cv_train = y_train.iloc[train_idx]\n",
    "    X_cv_val = X_train.iloc[val_idx]\n",
    "    y_cv_val = y_train.iloc[val_idx]\n",
    "    \n",
    "    cv_model = lgb.LGBMRegressor(n_estimators=100, learning_rate=0.05, num_leaves=63, n_jobs=-1)\n",
    "    cv_model.fit(X_cv_train, y_cv_train, eval_set=[(X_cv_val, y_cv_val)], callbacks=[lgb.early_stopping(20), lgb.log_evaluation(0)])\n",
    "    \n",
    "    cv_pred = cv_model.predict(X_cv_val)\n",
    "    cv_rmse = np.sqrt(mean_squared_error(np.expm1(y_cv_val), np.expm1(np.maximum(cv_pred, 0))))\n",
    "    print(f\"Fold {fold} RMSE: {cv_rmse:.4f}\")\n",
    "    fold += 1\n",
    "    del X_cv_train, y_cv_train, X_cv_val, y_cv_val, cv_model\n",
    "    gc.collect()\n",
    "print(\"✅ Cross-Validation Complete.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Train Item-Level Champion (LightGBM)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if 'X_train' in locals():\n",
    "    print(\"🚀 Training Final Tuned LightGBM...\")\n",
    "    # Create a proper validation set from the LAST 15% of training data chronologically\n",
    "    val_size = int(len(X_train) * 0.15)\n",
    "    X_val = X_train.iloc[-val_size:].copy()\n",
    "    y_val = y_train.iloc[-val_size:].copy()\n",
    "    X_tr = X_train.iloc[:-val_size].copy()\n",
    "    y_tr = y_train.iloc[:-val_size].copy()\n",
    "    \n",
    "    # Free memory\n",
    "    del X_train, y_train\n",
    "    gc.collect()\n",
    "\n",
    "    model = lgb.LGBMRegressor(\n",
    "        n_estimators=500, \n",
    "        learning_rate=0.05, \n",
    "        num_leaves=63,\n",
    "        colsample_bytree=0.8, \n",
    "        subsample=0.8, \n",
    "        random_state=42, \n",
    "        verbose=-1,\n",
    "        n_jobs=-1\n",
    "    )\n",
    "\n",
    "    # EARLY STOPPING FIX: Use X_val, y_val, not X_test\n",
    "    model.fit(\n",
    "        X_tr, y_tr, \n",
    "        eval_set=[(X_val, y_val)], \n",
    "        callbacks=[lgb.early_stopping(50), lgb.log_evaluation(100)]\n",
    "    )\n",
    "\n",
    "    lgb_pred = model.predict(X_test)\n",
    "    train_pred = model.predict(X_tr)\n",
    "    \n",
    "    # Compute train metrics (aggregated)\n",
    "    train_df = X_tr.copy()\n",
    "    train_df['date'] = pd.to_datetime(train_df[['year', 'month', 'day']])\n",
    "    train_df['pred_log'] = train_pred\n",
    "    train_df['actual_log'] = y_tr.values\n",
    "    daily_lgb_train = train_df.groupby('date').agg(\n",
    "        pred_qty=('pred_log', lambda x: np.expm1(np.maximum(x, 0)).sum()),\n",
    "        actual_qty=('actual_log', lambda x: np.expm1(x).sum())\n",
    "    ).reset_index()\n",
    "    t_act, t_pred = daily_lgb_train['actual_qty'].values, daily_lgb_train['pred_qty'].values\n",
    "    t_mask = t_act > 0\n",
    "    train_rmse = np.sqrt(mean_squared_error(t_act, t_pred))\n",
    "    train_mae = mean_absolute_error(t_act, t_pred)\n",
    "    train_mape = np.mean(np.abs((t_act[t_mask] - t_pred[t_mask]) / t_act[t_mask])) * 100\n",
    "    train_r2 = r2_score(t_act, t_pred)\n",
    "\n",
    "    # Aggregate back to daily quantities to compute MAPE properly (Apples to Apples)\n",
    "    test_df = X_test.copy()\n",
    "    test_df['date'] = pd.to_datetime(test_df[['year', 'month', 'day']])\n",
    "    test_df['pred_log'] = lgb_pred\n",
    "    test_df['actual_log'] = y_test.values\n",
    "    \n",
    "    daily_lgb = test_df.groupby('date').agg(\n",
    "        pred_qty=('pred_log', lambda x: np.expm1(np.maximum(x, 0)).sum()),\n",
    "        actual_qty=('actual_log', lambda x: np.expm1(x).sum())\n",
    "    ).reset_index()\n",
    "    \n",
    "    actuals = daily_lgb['actual_qty'].values\n",
    "    preds = daily_lgb['pred_qty'].values\n",
    "    mask = actuals > 0\n",
    "    \n",
    "    test_rmse = np.sqrt(mean_squared_error(actuals, preds))\n",
    "    test_mae = mean_absolute_error(actuals, preds)\n",
    "    test_mape = np.mean(np.abs((actuals[mask] - preds[mask]) / actuals[mask])) * 100\n",
    "    test_r2 = r2_score(actuals, preds)\n",
    "    \n",
    "    print(f\"\\n{'='*70}\")\n",
    "    print(f\"{'LIGHTGBM PERFORMANCE':^70}\")\n",
    "    print(f\"{'='*70}\")\n",
    "    print(f\"\\nTraining Set (Daily Aggregates):\")\n",
    "    print(f\"  RMSE: {train_rmse:.4f}\")\n",
    "    print(f\"  MAE:  {train_mae:.4f}\")\n",
    "    print(f\"  MAPE: {train_mape:.2f}%\")\n",
    "    print(f\"  R²:   {train_r2:.4f}\")\n",
    "    print(f\"\\nTest Set (Daily Aggregates):\")\n",
    "    print(f\"  RMSE: {test_rmse:.4f}\")\n",
    "    print(f\"  MAE:  {test_mae:.4f}\")\n",
    "    print(f\"  MAPE: {test_mape:.2f}%\")\n",
    "    print(f\"  R²:   {test_r2:.4f}\")\n",
    "    print(f\"\\n{'='*70}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Train Aggregate Champion (SARIMA)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"🚀 Training Aggregate SARIMA...\")\n",
    "try:\n",
    "    train_raw = pd.read_parquet(f'{data_dir}/train_raw.parquet')\n",
    "    test_raw = pd.read_parquet(f'{data_dir}/test_raw.parquet')\n",
    "    \n",
    "    sarima_train = train_raw.groupby('date')['quantity'].sum()\n",
    "    sarima_test = test_raw.groupby('date')['quantity'].sum()\n",
    "    \n",
    "    # Free memory\n",
    "    del train_raw, test_raw\n",
    "    gc.collect()\n",
    "    \n",
    "    # Use AutoARIMA to find the best parameters instead of hardcoding\n",
    "    print(\"⏳ Running Auto-ARIMA to find optimal parameters (this may take a minute)...\")\n",
    "    import pmdarima as pm\n",
    "    sarima_model = pm.auto_arima(\n",
    "        sarima_train, \n",
    "        seasonal=True, \n",
    "        m=7, \n",
    "        stepwise=True, \n",
    "        suppress_warnings=True, \n",
    "        error_action=\"ignore\",\n",
    "        trace=True\n",
    "    )\n",
    "    print(\"\\n✅ Auto-ARIMA Optimal Parameters Found:\")\n",
    "    print(sarima_model.summary())\n",
    "    \n",
    "    sarima_pred = sarima_model.predict(n_periods=len(sarima_test))\n",
    "    sarima_pred = np.maximum(np.nan_to_num(sarima_pred, nan=0.0), 0)\n",
    "    \n",
    "    actuals_s = sarima_test.values\n",
    "    preds_s = sarima_pred  # FIX: sarima_pred is already a numpy array\n",
    "    mask_s = actuals_s > 0\n",
    "    \n",
    "    rmse_s = np.sqrt(mean_squared_error(actuals_s, preds_s))\n",
    "    mae_s = mean_absolute_error(actuals_s, preds_s)\n",
    "    mape_s = np.mean(np.abs((actuals_s[mask_s] - preds_s[mask_s]) / actuals_s[mask_s])) * 100\n",
    "    r2_s = r2_score(actuals_s, preds_s)\n",
    "    \n",
    "    print(f\"\\n✅ SARIMA Aggregate Performance:\")\n",
    "    print(f\"RMSE: {rmse_s:.4f}\")\n",
    "    print(f\"MAE:  {mae_s:.4f}\")\n",
    "    print(f\"MAPE: {mape_s:.4f}%\")\n",
    "    print(f\"R²:   {r2_s:.4f}\")\n",
    "    \n",
    "    # Generate daily predictions to use in the plot\n",
    "    daily_pred_s = pd.DataFrame({'date': sarima_test.index, 'pred_qty': preds_s})\n",
    "except Exception as e:\n",
    "    print(\"⚠️ Failed to train SARIMA:\", e)\n",
    "    daily_pred_s = None\n",
    "    raise e"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Final Performance Dashboard & Model Export"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if 'model' in locals():\n",
    "    fig, ax = plt.subplots(1, 3, figsize=(22, 6))\n",
    "\n",
    "    # Feature Importance\n",
    "    imp = pd.Series(model.feature_importances_, index=X_tr.columns).sort_values()\n",
    "    imp.tail(15).plot(kind='barh', ax=ax[0], color='steelblue')\n",
    "    ax[0].set_title(\"LightGBM Feature Importance (Top 15)\")\n",
    "    ax[0].grid(axis='x', alpha=0.3)\n",
    "\n",
    "    # Residual Distribution (Bias Check)\n",
    "    residuals = actuals - preds\n",
    "    print(f\"\\n🔍 BIAS CHECK: Mean Residual = {residuals.mean():.4f} (Positive = Under-forecasting, Negative = Over-forecasting)\")\n",
    "    \n",
    "    sns.histplot(residuals, bins=50, ax=ax[1], kde=True, color='darkorange')\n",
    "    ax[1].set_title(\"Error Distribution (Actuals - Preds)\")\n",
    "    # Fix x-axis to 1st and 99th percentiles\n",
    "    p1, p99 = np.percentile(residuals, 1), np.percentile(residuals, 99)\n",
    "    ax[1].set_xlim(p1, p99)\n",
    "    ax[1].grid(alpha=0.3)\n",
    "\n",
    "    # Forecast vs Actual Line Plot\n",
    "    ax[2].plot(daily_lgb['date'], actuals, label='Actual Demand', color='black', alpha=0.7)\n",
    "    ax[2].plot(daily_lgb['date'], preds, label='LightGBM Pred', color='steelblue', alpha=0.9)\n",
    "    if daily_pred_s is not None:\n",
    "        ax[2].plot(daily_pred_s['date'], daily_pred_s['pred_qty'], label='SARIMA Pred', color='darkorange', alpha=0.9, linestyle='--')\n",
    "    ax[2].set_title(\"Forecast vs Actual (Daily Aggregates)\")\n",
    "    ax[2].legend()\n",
    "    ax[2].grid(alpha=0.3)\n",
    "    plt.xticks(rotation=45)\n",
    "\n",
    "    plt.tight_layout()\n",
    "    plt.savefig('final_model_performance.png', dpi=300)\n",
    "    plt.show()\n",
    "\n",
    "    # SAVE MODEL AND METADATA AFTER VALIDATION PASSES\n",
    "    os.makedirs('trained_models', exist_ok=True)\n",
    "    \n",
    "    model_path = 'trained_models/lgb_model.pkl'\n",
    "    with open(model_path, 'wb') as f:\n",
    "        pickle.dump(model, f)\n",
    "    print(f\"✓ Model saved: {model_path}\")\n",
    "    \n",
    "    if 'sarima_model' in locals():\n",
    "        with open('trained_models/sarima_model_final.pkl', 'wb') as f:\n",
    "            pickle.dump(sarima_model, f)\n",
    "            \n",
    "    # Save metadata for dashboard\n",
    "    metadata = {\n",
    "        'feature_names': FEATURES,\n",
    "        'model_type': 'LightGBM',\n",
    "        'metrics': {\n",
    "            'train_rmse': float(train_rmse),\n",
    "            'train_mae': float(train_mae),\n",
    "            'train_mape': float(train_mape),\n",
    "            'train_r2': float(train_r2),\n",
    "            'test_rmse': float(test_rmse),\n",
    "            'test_mae': float(test_mae),\n",
    "            'test_mape': float(test_mape),\n",
    "            'test_r2': float(test_r2),\n",
    "        }\n",
    "    }\n",
    "    \n",
    "    metadata_path = 'trained_models/model_metadata.pkl'\n",
    "    with open(metadata_path, 'wb') as f:\n",
    "        pickle.dump(metadata, f)\n",
    "    print(f\"✓ Metadata saved: {metadata_path}\")\n",
    "    \n",
    "    print(f\"\\n{'='*70}\")\n",
    "    print(f\"✓✓✓ PIPELINE COMPLETE - READY FOR PRODUCTION\")\n",
    "    print(f\"{'='*70}\")\n",
    "    print(f\"\\nAll artifacts exported successfully!\")\n",
    "    print(f\"Next: streamlit run dashboard.py\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

with open("3_final_modeling.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)
